### ISSUE TITLE
[Usersnap] Picture doesn't load for me or my partner. Displays alt instead.

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/career-services-full-stack#10]
Usersnap feedback [5047](https://app.usersnap.com/l/feedback/e7cc81e0-1656-476a-a606-7670e8b7949f?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://full-time.learnhowtoprogram.com/career-services/applying-for-internships-and-jobs/identifying-important-skills

Text: Picture doesn't load for me or my partner. Displays alt instead.

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/5aabdf60-8d9f-4f44-ae58-b6544bd36b85-annotated_98046632-478e-4819-aed6-7e4f0940f3e6.png?etag=0cf6ceb61eb966ee3f27813041caceaa

**Comment by erik-t-irgens** [comment]
Fixed!
