### ISSUE TITLE
[Usersnap] Example Wordcloud photo is missing

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/career-services-full-stack#11]
Usersnap feedback [5048](https://app.usersnap.com/l/feedback/477d4793-7a4e-4b3b-b6c0-9d8675ee535a?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://full-time.learnhowtoprogram.com/career-services/applying-for-internships-and-jobs/identifying-important-skills

Text: Example Wordcloud photo is missing

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/daa3157c-52ae-4133-9bba-14f87ee41057-annotated_6b23603c-a6a1-45af-8c2f-3fd3ccc8c63a.png?etag=00f705a72c4a8eb19b72530307c4a607

**Comment by erik-t-irgens** [comment]
Fixed!
