### ISSUE TITLE
[Usersnap] The photo did not load.

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/career-services-full-stack#12]
Usersnap feedback [5050](https://app.usersnap.com/l/feedback/a78ad84a-6ea4-4f3f-aa70-865db24dc306?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://full-time.learnhowtoprogram.com/career-services/applying-for-internships-and-jobs/identifying-important-skills

Text: The photo did not load.

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/c1b5f775-60f9-425a-973c-4851cbc7a4f3-annotated_77477a49-8ad3-4d12-a328-3780a4ca2961.png?etag=96221105e6df9db77b99887f8a9d50cb

**Comment by erik-t-irgens** [comment]
It seems that the problem has been fixed!
